extends:
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
plugins:
  - stylelint-order
rules:
  # Case
  value-keyword-case:
    - lower
    - camelCaseSvgKeywords: true
  # Max & min
  declaration-block-single-line-max-declarations: 1
  # Pattern
  selector-class-pattern: null
